### ISSUE TITLE
Support for IntelliJ 2022.2

### ISSUE THREAD

**Issue by renataogarcia** [AVeenstra/RunAnything#7]
The plugins currently fails with "Incompatible: requires IDE build 221.* or earlier" on Intellij 2022.2.

**Comment by AVeenstra** [comment]
I removed the upper version limit, which should reduce the number of times I need to update the plugin.

The new version should be available in a day or two on the Jetbrains marketplace. This same version is also available in the releases section of this project:
https://github.com/AVeenstra/RunAnything/releases/tag/1.11
